#pragma once
#include <stdint.h>

static const char* const phoneme_to_label[] = {
    /* 0  IY */  "IY",
    /* 1  IH */  "IH",
    /* 2  EH */  "EH",
    /* 3  AE */  "AE",
    /* 4  IX */  "IX",
    /* 5  AX */  "AX",
    /* 6  ER */  "ER",
    /* 7  AH */  "AH",
    /* 8  AA */  "AA",
    /* 9  AO */  "AO",
    /* 10 UH */  "UH",
    /* 11 UW */  "UW",
    /* 12 EY */  "EY",
    /* 13 AY */  "AY",
    /* 14 OY */  "OY",
    /* 15 AW */  "AW",
    /* 16 OW */  "OW",
    /* 17 YU */  "YU",
    /* 18 IR */  "IR",
    /* 19 XR */  "XR",
    /* 20 AR */  "AR",
    /* 21 OR */  "OR",
    /* 22 UR */  "UR",
    /* 23 SIL */ NULL,
    /* 24 M  */  "M",
    /* 25 N  */  "N",
    /* 26 NG */  "NG",
    /* 27 W  */  "W",
    /* 28 Y  */  "Y",
    /* 29 R  */  "R",
    /* 30 L  */  "L",
    /* 31 RX */  "RX",
    /* 32 LX */  "LX",
    /* 33 EL */  "EL",
    /* 34 EN */  "EN",
    /* 35 F  */  "F",
    /* 36 V  */  "V",
    /* 37 TH */  "TH",
    /* 38 DH */  "DH",
    /* 39 S  */  "S",
    /* 40 Z  */  "Z",
    /* 41 SH */  "SH",
    /* 42 ZH */  "ZH",
    /* 43 HH */  "HH",
    /* 44 P  */  "P",
    /* 45 B  */  "B",
    /* 46 T  */  "T",
    /* 47 D  */  "D",
    /* 48 K  */  "K",
    /* 49 G  */  "G",
    /* 50 CH */  "CH",
    /* 51 JH */  "JH",
    /* 52 TX */  "TX",
    /* 53 DX */  "DX",
    /* 54 QX */  "QX",
    /* 55 DD */  "DD",
    /* 56 JP_A */"A",
    /* 57 JP_I */"I",
    /* 58 JP_U */"U",
    /* 59 JP_E */"E",
    /* 60 JP_O */"O",
};
#define PHONEME_LABEL_COUNT ((int)(sizeof(phoneme_to_label)/sizeof(phoneme_to_label[0])))
